### ISSUE TITLE
Any plan to share on Hugging Face ?

### ISSUE THREAD

**Issue by lhoestq** [facebookresearch/belebele#1]
Hi ! I'm Quentin from HF :)

Thanks for sharing this dataset ! I'm glad to see more non-english-only datasets to evaluate models.

Do you plan to share it on HF ? This would allow everyone to load it in one line of python (and choosing language). There is also a dataset viewer + search for those who want to explore the data.

**Comment by lucasbandarkar** [comment]
@lhoestq Dataset can be found here https://huggingface.co/datasets/facebook/belebele, thanks for the patience
