### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by geronimi73** [facebookresearch/belebele#2]
would be great if you could share the code you used to evaluate llama2 for example
just a few lines. please 😘

**Comment by lucasbandarkar** [comment]
Hey @geronimi73, please refer to Section 4.2 for the paper, it has all the details of how we evaluated Llama 2. We used internal Meta tooling for it, but we describe the exact prompts we used.

We are working with HF to maybe display some code for it, but that is still TBD
