### ISSUE TITLE
Incorrect URL for Ancient China

### ISSUE THREAD

**Issue by e-vandenberg** [facebookresearch/belebele#3]
The URL for the ancient China question is given as https://en.wikibooks.org/wiki/Ancient_China/Government which doesn't exist. 

The correct URL is https://en.wikibooks.org/wiki/Chinese_History/Government. The required passage, "Ancient China had a unique way of showing different..." is present in this wikibooks page.

**Comment by lucasbandarkar** [comment]
Hey @e-vandenberg, thanks for pointing this out. Unfortunately, this is an issue from the original https://github.com/facebookresearch/flores/blob/main/flores200/README.md, and modifying that dataset was out of scope.
